const express = require("express")
const Task = require("../../../models/task.model")
const pagination = require("../../../helpers/pagination")
const searchHelper =require("../../../helpers/search")
const controller =require("../../../controllers/task.controller")
const router = express.Router()
router.get("/", controller.index)
router.get("/detail/:id", controller.detail)
router.patch("/change-status/:id", controller.changeStatus)
router.patch("/change-multi", controller.changeMulti)
router.post("/create",controller.create)
router.patch("/update/:id", controller.update)
router.delete("/delete/:id", controller.delete)
module.exports =router